# Generated by Django 2.0.5 on 2018-06-01 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='editordata',
            name='name',
            field=models.CharField(default='Jeff', max_length=10),
        ),
        migrations.AlterField(
            model_name='editordata',
            name='lastModified',
            field=models.CharField(default='1 Jan 1970', max_length=50),
        ),
    ]
