# Generated by Django 2.0.5 on 2018-06-01 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EditorData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('htmlContent', models.TextField()),
                ('showHTML', models.TextField()),
                ('lastModified', models.CharField(max_length=50)),
            ],
        ),
    ]
